### ISSUE TITLE
Latest nPlates

### ISSUE THREAD

**Issue by Technojo01** [Grimsbain/nPlates#1]
When looking at NPCs

Message: Interface\AddOns\nPlates\core.lua:203: attempt to index field 'healthString' (a nil value)
Time: 08/02/16 07:53:56
Count: 1
Stack: Interface\AddOns\nPlates\core.lua:203: in function <Interface\AddOns\nPlates\core.lua:191>
[C]: in function `CompactUnitFrame_UpdateStatusText'
Interface\FrameXML\CompactUnitFrame.lua:294: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:171: in function `CompactUnitFrame_SetUnit'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:270: in function `OnAdded'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:59: in function `OnNamePlateAdded'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:24: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:18>

Locals: frame = NamePlate1UnitFrame {
 otherHealPrediction = <unnamed> {
 }
 LoseAggroAnim = <unnamed> {
 }
 selectionHighlight = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
 classificationIndicator = <unnamed> {
 }
 myHealAbsorbLeftShadow = <unnamed> {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 inVehicle = false
 0 = <userdata>
 statusText = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 castBar = <unnamed> {
 }
 displayedUnit = "nameplate1"
 unitExists = true
 optionTable = <table> {
 }
 overAbsorbGlow = <unnamed> {
 }
 maxBuffs = 0
 BuffFrame = <unnamed> {
 }
 healthBar = <unnamed> {
 }
 totalAbsorbOverlay = <unnamed> {
 }
 totalAbsorb = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 newUnit = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "nameplate"
(*temporary) = "nameplate"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'healthString' (a nil value)"
FormatValue = <function> defined @Interface\AddOns\nPlates\core.lua:74

**Comment by Technojo01** [comment]
hmm, turning back on Display Health text and off, now it seems ok. Weird.

**Comment by Grimsbain** [comment]
Thanks for the report. I added an additional check to make sure this doesn't happen.
