### ISSUE TITLE
Health Text showing on RaidFrame

### ISSUE THREAD

**Issue by clicketz** [Grimsbain/nPlates#17]
As of the latest update, health text from this addon is also appearing on raid frames.

Think you're just missing this in the UpdateStatusText hook

```Lua
if ( not frame.isNameplate ) then return end
```

**Comment by Grimsbain** [comment]
Thanks should be fixed with the new version. The fix you suggested was a good idea but I had to do it slightly different to keep it from sometimes not showing the text.
