### ISSUE TITLE
Defaul Auras (buffs/debuffs) frame glith

### ISSUE THREAD

**Issue by Beton** [Grimsbain/nPlates#18]
Hey, enabling nPlates I have noticed that there is pretty annoying visual gap between Nameplate and default Auras frame (see screenshot). 

The issue is not present on not selected nameplates.

![WoWScrnShot_012821_145958](https://user-images.githubusercontent.com/354028/106148941-f5572c00-6179-11eb-9218-440676ff9a1b.jpg)

**Comment by Grimsbain** [comment]
Fixed with 2.74.
