### ISSUE TITLE
10.1 Broke 

### ISSUE THREAD

**Issue by Nutrition1** [Grimsbain/nPlates#23]
Hi,

Config Menu no longer opens and addon throwing out lua errors

Message: Interface/AddOns/nPlates/Settings.lua:41: attempt to call global 'GetAddOnMetadata' (a nil value)

Time: Mon May  8 00:13:37 2023

Count: 1

Stack: Interface/AddOns/nPlates/Settings.lua:41: attempt to call global 'GetAddOnMetadata' (a nil value)

[string "@Interface/AddOns/nPlates/Settings.lua"]:41: in function 

 

Locals: self = nPlatesOptions {

 SaveProfileBackup =  defined @Interface/AddOns/nPlates/Settings.lua:58

 OnLoad =  defined @Interface/AddOns/nPlates/Settings.lua:34

 SaveChanges =  defined @Interface/AddOns/nPlates/Settings.lua:62

 controls =  {

 }

 RightSide = nPlatesOptionsRightSide {

 }

 OnEvent =  defined @Interface/AddOns/nPlates/Settings.lua:50

 CancelChanges =  defined @Interface/AddOns/nPlates/Settings.lua:77

 UpdatePanel =  defined @Interface/AddOns/nPlates/Settings.lua:94

 LeftSide = nPlatesOptionsLeftSide {

 }

 profileBackup = 

 {
 }

 RestoreDefaults =  defined @Interface/AddOns/nPlates/Settings.lua:86

 ShouldUpdate =  defined @Interface/AddOns/nPlates/Settings.lua:70

 0 = 

 Init =  defined @Interface/AddOns/nPlates/Settings.lua:102

}

(*temporary) = nil

(*temporary) = "nPlates"

(*temporary) = "Title"

(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

addon = "nPlates"

**Comment by Grimsbain** [comment]
Thanks for the report. Should be fixed now. They updated the GetAddOnMetadata function to C_AddOns.GetAddOnMetadata with the new patch.
