### ISSUE TITLE
Error friendly nameplates

### ISSUE THREAD

**Issue by rakkarage** [Grimsbain/nPlates#4]
When I turn on friendly nameplates I get errors?
- Tried after disable all other addons.
- Tried after deleting Cache & Interface & Wtf.

> Message: Interface\AddOns\nPlates\core.lua:395: Attempt to access forbidden object from code tainted by an AddOn
> Time: 04/07/17 10:09:26
> Count: 4
> Stack: [C]: in function `SetHeight'
> Interface\AddOns\nPlates\core.lua:395: in function <Interface\AddOns\nPlates\core.lua:394>
> [C]: in function `DefaultCompactNamePlateFrameSetupInternal'
> Interface\FrameXML\CompactUnitFrame.lua:1750: in function <Interface\FrameXML\CompactUnitFrame.lua:1732>
> [C]: in function `DefaultCompactNamePlateFrameSetup'
> Interface\FrameXML\CompactUnitFrame.lua:1754: in function `func'
> Interface\FrameXML\CompactUnitFrame.lua:201: in function `CompactUnitFrame_SetUpFrame'
> ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108: in function `ApplyFrameOptions'
> ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84: in function `OnNamePlateAdded'
> ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:35>
> 
> Locals: (*temporary) = <unnamed> {
>  otherHealPrediction = <unnamed> {
>  }
>  overAbsorbGlow = <unnamed> {
>  }
>  myHealAbsorbLeftShadow = <unnamed> {
>  }
>  border = <unnamed> {
>  }
>  barTexture = <unnamed> {
>  }
>  totalAbsorb = <unnamed> {
>  }
>  myHealAbsorb = <unnamed> {
>  }
>  myHealPrediction = <unnamed> {
>  }
>  myHealAbsorbRightShadow = <unnamed> {
>  }
>  0 = <userdata>
>  background = <unnamed> {
>  }
>  overHealAbsorbGlow = <unnamed> {
>  }
>  totalAbsorbOverlay = <unnamed> {
>  }
> }
> (*temporary) = 12
>

**Comment by Grimsbain** [comment]
I can't seem to find problem. Did you have any other addons that changed the personal resource display?

**Comment by rakkarage** [comment]
Thanks for the reply. I guess it does seem like my problem since no one else anywhere has reported this.

I am not sure exactly what you mean by personal resource display but I did have AdvancedInterfaceOptions installed and was messing around with all the nameplate settings...
And I tried with the interface nameplate resource display option check and not...
And I tried on non-pvp server and I tried on alliance character and I tried 32-bit...
And I tried blizzard repair...

But now I have deleted everything and reset user options and even reset /console cvar_default so I do not know what could be affecting it?

/console taintLog 1 shows nothing but /console taintLog 2 shows:
https://gist.github.com/rakkarage/b15902053166e85b8e9bc5ca7bf65b66
4/10 12:40:42.041  Global variable SLASH_nplates1 tainted by nPlates - Interface\AddOns\nPlates\slash.lua:35

4/10 12:40:46.087  Global variable EVENT_TRACE_EVENT_HEIGHT tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:1

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EVENT_TRACE_MAX_ENTRIES tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:2

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable DEBUGLOCALS_LEVEL tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:4

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EVENT_TRACE_SYSTEM_TIMES tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:7

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EVENT_TRACE_EVENT_COLORS tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:11

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EventTraceFrame_OnLoad tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:23

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EventTraceFrame_OnEvent tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:48

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EventTraceFrame_OnShow tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:126

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EventTraceFrame_OnUpdate tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:133

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EventTraceFrame_OnSizeChanged tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:137

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

4/10 12:40:46.087  Global variable EventTraceFrame_Update tainted by nPlates - Interface\AddOns\Blizzard_DebugTools\Blizzard_DebugTools.lua:167

4/10 12:40:46.087      LoadAddOn()

4/10 12:40:46.087      Interface\FrameXML\BasicControls.xml:<Scripts>:5

4/10 12:40:46.087      <unnamed>:SetHeight()

4/10 12:40:46.087      Interface\AddOns\nPlates\core.lua:395

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetupInternal()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1750

4/10 12:40:46.087      DefaultCompactNamePlateFrameSetup()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:1754 func()

4/10 12:40:46.087      Interface\FrameXML\CompactUnitFrame.lua:201 CompactUnitFrame_SetUpFrame()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108 NamePlateDriverFrame:ApplyFrameOptions()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:84 NamePlateDriverFrame:OnNamePlateAdded()

4/10 12:40:46.087      Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44

etc...

**Comment by rakkarage** [comment]
here is a gif
https://giphy.com/gifs/3ohzdLhk9MO6MUr8fm/html5

**Comment by rakkarage** [comment]
"Friendly nameplates in dungeons/raids were made protected by Blizzard in 7.2,
nPlates apparently has to be updated to not work in dungeons for friendly nameplates"

**Comment by rakkarage** [comment]
http://www.wowhead.com/news=260801/addons-friendly-nameplates-in-patch-7-2

**Comment by Grimsbain** [comment]
Thanks for finding that. That was the problem and I think I got it worked out in the new version.

**Comment by Grimsbain** [comment]
Woops, had some messed up comments should be fixed now.

**Comment by rakkarage** [comment]
works. woohoo. thanks.
