### ISSUE TITLE
Personal resource position error

### ISSUE THREAD

**Issue by daneras** [Grimsbain/nPlates#8]
Hello Grimsbain,

i have a little error at the looking of the personal resource nPlates. As you can see on the attached screen, i'm not in a raid or group. The PR is on the bottom left screen and no the nPlate design.

I can't get it away with /rl in or out of combat. If i die (f.e.) it will reset it. It will happen also on windows or mac client.

Can a do something that this is not gona happen?

Greetings,
Daneras

![bildschirmfoto 2017-09-11 um 11 37 01](https://user-images.githubusercontent.com/20454019/30268738-f5e07282-96e6-11e7-9c7c-8d51cbd702fa.jpg)

**Comment by Grimsbain** [comment]
I think I have this fixed now. Try the newest version (2.41) if you run into any problems let me know.

**Comment by daneras** [comment]
Many thanks Grim, i will test it today.
